-- phpMyAdmin SQL Dump
-- version 4.5.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: 08-Jul-2018 às 11:07
-- Versão do servidor: 5.7.21
-- PHP Version: 5.6.23-1+deprecated+dontuse+deb.sury.org~trusty+1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `issuer`
--

-- --------------------------------------------------------

--
-- Estrutura da tabela `issue`
--

CREATE TABLE `issue` (
  `id` int(11) NOT NULL,
  `number` int(11) NOT NULL,
  `issue` text NOT NULL,
  `action` varchar(255) NOT NULL,
  `labels` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Extraindo dados da tabela `issue`
--

INSERT INTO `issue` (`id`, `number`, `issue`, `action`, `labels`) VALUES
(1, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":null,"comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"open","title":"Test","updated_at":"2018-07-07T22:03:04Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'reopened', ''),
(2, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":"2018-07-07T22:04:46Z","comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"closed","title":"Test","updated_at":"2018-07-07T22:04:46Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'closed', ''),
(3, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":null,"comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"open","title":"Test","updated_at":"2018-07-07T22:08:27Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'reopened', ''),
(4, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":null,"comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"open","title":"Test","updated_at":"2018-07-08T00:28:11Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'reopened', '[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}]'),
(5, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":"2018-07-08T00:28:16Z","comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"closed","title":"Test","updated_at":"2018-07-08T00:28:16Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'closed', '[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}]'),
(6, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":null,"comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"open","title":"Test","updated_at":"2018-07-08T00:28:51Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'reopened', '[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}]'),
(7, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":"2018-07-08T00:31:42Z","comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"closed","title":"Test","updated_at":"2018-07-08T00:31:42Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'closed', '[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}]'),
(8, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":null,"comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"open","title":"Test","updated_at":"2018-07-08T00:33:07Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'reopened', '[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}]'),
(9, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":"2018-07-08T00:37:44Z","comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"closed","title":"Test","updated_at":"2018-07-08T00:37:44Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'closed', '[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}]'),
(10, 2, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"It looks like you accidently spelled ''commit'' with two ''t''s.","closed_at":null,"comments":0,"comments_url":"https://api.github.com/repos/Codertocat/Hello-World/issues/2/comments","created_at":"2018-05-30T20:18:32Z","events_url":"https://api.github.com/repos/Codertocat/Hello-World/issues/2/events","html_url":"https://github.com/Codertocat/Hello-World/issues/2","id":327883527,"labels":[{"color":"d73a4a","default":true,"id":949737505,"name":"bug","node_id":"MDU6TGFiZWw5NDk3Mzc1MDU=","url":"https://api.github.com/repos/Codertocat/Hello-World/labels/bug"}],"labels_url":"https://api.github.com/repos/Codertocat/Hello-World/issues/2/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjc4ODM1Mjc=","number":2,"repository_url":"https://api.github.com/repos/Codertocat/Hello-World","state":"open","title":"Spelling error in the README file","updated_at":"2018-05-30T20:18:32Z","url":"https://api.github.com/repos/Codertocat/Hello-World/issues/2","user":{"avatar_url":"https://avatars1.githubusercontent.com/u/21031067?v=4","events_url":"https://api.github.com/users/Codertocat/events{/privacy}","followers_url":"https://api.github.com/users/Codertocat/followers","following_url":"https://api.github.com/users/Codertocat/following{/other_user}","gists_url":"https://api.github.com/users/Codertocat/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/Codertocat","id":21031067,"login":"Codertocat","node_id":"MDQ6VXNlcjIxMDMxMDY3","organizations_url":"https://api.github.com/users/Codertocat/orgs","received_events_url":"https://api.github.com/users/Codertocat/received_events","repos_url":"https://api.github.com/users/Codertocat/repos","site_admin":false,"starred_url":"https://api.github.com/users/Codertocat/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Codertocat/subscriptions","type":"User","url":"https://api.github.com/users/Codertocat"}}', 'edited', '[{"color":"d73a4a","default":true,"id":949737505,"name":"bug","node_id":"MDU6TGFiZWw5NDk3Mzc1MDU=","url":"https://api.github.com/repos/Codertocat/Hello-World/labels/bug"}]'),
(11, 2, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"It looks like you accidently spelled ''commit'' with two ''t''s.","closed_at":null,"comments":0,"comments_url":"https://api.github.com/repos/Codertocat/Hello-World/issues/2/comments","created_at":"2018-05-30T20:18:32Z","events_url":"https://api.github.com/repos/Codertocat/Hello-World/issues/2/events","html_url":"https://github.com/Codertocat/Hello-World/issues/2","id":327883527,"labels":[{"color":"d73a4a","default":true,"id":949737505,"name":"bug","node_id":"MDU6TGFiZWw5NDk3Mzc1MDU=","url":"https://api.github.com/repos/Codertocat/Hello-World/labels/bug"}],"labels_url":"https://api.github.com/repos/Codertocat/Hello-World/issues/2/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjc4ODM1Mjc=","number":2,"repository_url":"https://api.github.com/repos/Codertocat/Hello-World","state":"open","title":"Spelling error in the README file","updated_at":"2018-05-30T20:18:32Z","url":"https://api.github.com/repos/Codertocat/Hello-World/issues/2","user":{"avatar_url":"https://avatars1.githubusercontent.com/u/21031067?v=4","events_url":"https://api.github.com/users/Codertocat/events{/privacy}","followers_url":"https://api.github.com/users/Codertocat/followers","following_url":"https://api.github.com/users/Codertocat/following{/other_user}","gists_url":"https://api.github.com/users/Codertocat/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/Codertocat","id":21031067,"login":"Codertocat","node_id":"MDQ6VXNlcjIxMDMxMDY3","organizations_url":"https://api.github.com/users/Codertocat/orgs","received_events_url":"https://api.github.com/users/Codertocat/received_events","repos_url":"https://api.github.com/users/Codertocat/repos","site_admin":false,"starred_url":"https://api.github.com/users/Codertocat/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/Codertocat/subscriptions","type":"User","url":"https://api.github.com/users/Codertocat"}}', 'edited', '[{"color":"d73a4a","default":true,"id":949737505,"name":"bug","node_id":"MDU6TGFiZWw5NDk3Mzc1MDU=","url":"https://api.github.com/repos/Codertocat/Hello-World/labels/bug"}]'),
(12, 1, '{"assignee":null,"assignees":[],"author_association":"OWNER","body":"","closed_at":null,"comments":1,"comments_url":"https://api.github.com/repos/alustau/math/issues/1/comments","created_at":"2018-05-13T17:37:49Z","events_url":"https://api.github.com/repos/alustau/math/issues/1/events","html_url":"https://github.com/alustau/math/issues/1","id":322612827,"labels":[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}],"labels_url":"https://api.github.com/repos/alustau/math/issues/1/labels{/name}","locked":false,"milestone":null,"node_id":"MDU6SXNzdWUzMjI2MTI4Mjc=","number":1,"repository_url":"https://api.github.com/repos/alustau/math","state":"open","title":"Test","updated_at":"2018-07-08T00:41:59Z","url":"https://api.github.com/repos/alustau/math/issues/1","user":{"avatar_url":"https://avatars0.githubusercontent.com/u/2944692?v=4","events_url":"https://api.github.com/users/alustau/events{/privacy}","followers_url":"https://api.github.com/users/alustau/followers","following_url":"https://api.github.com/users/alustau/following{/other_user}","gists_url":"https://api.github.com/users/alustau/gists{/gist_id}","gravatar_id":"","html_url":"https://github.com/alustau","id":2944692,"login":"alustau","node_id":"MDQ6VXNlcjI5NDQ2OTI=","organizations_url":"https://api.github.com/users/alustau/orgs","received_events_url":"https://api.github.com/users/alustau/received_events","repos_url":"https://api.github.com/users/alustau/repos","site_admin":false,"starred_url":"https://api.github.com/users/alustau/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/alustau/subscriptions","type":"User","url":"https://api.github.com/users/alustau"}}', 'reopened', '[{"color":"d73a4a","default":true,"id":890343872,"name":"bug","node_id":"MDU6TGFiZWw4OTAzNDM4NzI=","url":"https://api.github.com/repos/alustau/math/labels/bug"}]');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `issue`
--
ALTER TABLE `issue`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `issue`
--
ALTER TABLE `issue`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=13;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
